#!/bin/sh
### BEGIN INIT INFO
# Provides: jungle-team
# Default-Start:  2345
# Default-Stop:   016
# Short-Description: Daemon junglebot
# Description: Script para arrancar el bot de jungle-team
### END INIT INFO
# Source function library.
. /etc/init.d/functions

DAEMON=/usr/bin/junglebot/bot.py
NAME=junglebot
DESC="Script para arrancar el bot de jungle-team"
PIDFILE=/var/run/$NAME.pid
ARGS=""

test -f $DAEMON || exit 0

set -e

case "$1" in
    start)
        echo -n "* starting $DESC: $NAME... "
        start-stop-daemon -S -b -x $DAEMON -p $PIDFILE -m -- $ARGS
        echo "done."
        ;;
    stop)
        echo -n "* stopping $DESC: $NAME... "
	start-stop-daemon -K -p $PIDFILE
	rm -f $PIDFILE
        echo "done."
        ;;
    restart)
        echo "* restarting $DESC: $NAME... "
        $0 stop || true
        $0 start
        echo "done."
        ;;
    status)
        PROCESO=`status /usr/bin/python ${DAEMON} | grep running | wc -l`
        if [ "$PROCESO" -gt 0 ]
        then
           echo "Bot $NAME esta funcionando correctamente"
        else
           echo "Bot $NAME no esta funcionando correctamente"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
