#!/bin/sh

if [ ! -f /etc/opkg/jungle-feed.conf ];
then
    wget http://tropical.jungle-team.online/script/jungle-feed.conf -P /etc/opkg/
fi

pip install --upgrade setuptools
pip install -r /usr/bin/junglebot/requirements.txt

chmod 755 /usr/bin/junglebot/bot.py
/etc/init.d/junglebot-daemon start

