#!/bin/sh

if [ ! -f /etc/opkg/jungle-feed.conf ];
then
    wget http://tropical.jungle-team.online/script/jungle-feed.conf -P /etc/opkg/
fi

pip install --upgrade setuptools
pip install -r /usr/bin/junglebot/requirements.txt

chmod 755 /usr/bin/junglebot/bot.py
rm -f /etc/rc3.d/S98junglebot-daemon
cd /etc/rc3.d
ln -sf ../init.d/junglebot-daemon S98junglebot-daemon

/etc/init.d/junglebot-daemon start

