#!/bin/sh 

/etc/init.d/junglebot-daemon stop

DISTRO=$(cat /etc/opkg/all-feed.conf | cut -d'-' -f1 | awk '{ print $2 }')
if [ "${DISTRO}" == "VTi" ] || [ "${DISTRO}" == "pure2" ];
then
    #curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py   
    curl https://bootstrap.pypa.io/2.7/get-pip.py --output /tmp/get-pip.py
    python /tmp/get-pip.py
fi
